version: '3.7'

services:

  mongo:
    container_name: workshop-mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  rabbitmq:
    container_name: workshop-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'

networks:
  default:
    name: workshop-network
